create extension if not exists "pgcrypto";
create table if not exists inspection_requests (
 id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), updated_at timestamptz default now(), customer_name text not null, customer_email text not null, customer_phone text not null, car_brand text not null, car_model text not null, car_year text, car_plate text, seller_city text not null, seller_address text not null, preferred_date date, preferred_time text, service_type text not null, message text, status text default 'new' check (status in ('new','contacted','scheduled','completed','cancelled','archived')), admin_notes text, source text, privacy_accepted boolean not null default false, marketing_accepted boolean default false
);
create table if not exists services (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, description text, price_from numeric, features jsonb default '[]', is_active boolean default true, sort_order int default 0);
create table if not exists faqs (id uuid primary key default gen_random_uuid(), question text not null, answer text not null, category text, is_active boolean default true, sort_order int default 0);
create table if not exists testimonials (id uuid primary key default gen_random_uuid(), customer_name text not null, rating int check(rating between 1 and 5), content text not null, city text, is_active boolean default true, sort_order int default 0);
create table if not exists seo_pages (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, meta_title text, meta_description text, content text, excerpt text, focus_keyword text, status text default 'draft', published_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists admin_users (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, full_name text, role text default 'admin', created_at timestamptz default now());
